<script src="<?php echo base_url('public/assets/js/vendors/jquery.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/bootstrap.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/enquire.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/jquery.enllax.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/jquery.form-validator.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/jquery.touchSwipe.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/pace.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/slick.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/wow.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/jquery.navScroll.min.js') ?>"></script><!-- This assets are not avalaible in npm.js or it has been costumized-->
<script src="<?php echo base_url('public/assets/js/vendors/modernizr-2.8.3-respond-1.4.2.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/materialize.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/jquery.animateSlider.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/vanta/three.r92.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/vendors/vanta/vanta.net.min.js') ?>"></script>
<script src="<?php echo base_url('public/assets/js/scripts.js') ?>"></script>